### ISSUE TITLE
Spellcheck or "did you mean" on word 404

### ISSUE THREAD

**Issue by dancrew32** [makkoncept/pyvoc#1]
Cool module! Just a suggestion:

On 404 or maybe even before hitting the API, it would be worth it to check a dictionary or get a suggestion.

https://github.com/makkoncept/pyvoc/blob/f5c1886bd6093646e47cb1b222b86e0d8ef122ee/pyvoc/pyvoc.py#L106

```bash
pip3 install enchant
```

```python
import enchant
d = enchant.Dict('en_US')
print(d.check('chese'))  # False
print(d.check('chese'))  # ['cheese', 'these', 'chase', 'chose', 'chess', 'chest', 'Chester', 'Cheslie', 'Cheston', 'Cheshire']
```

**Comment by makkoncept** [comment]
@dancrew32 thanks for this issue. It looks like a good feature to have. I will add it in the next release.

**Comment by makkoncept** [comment]
Hi @dancrew32, I have added this feature in v.1.2.0. 
Thanks for suggesting it :)
