### ISSUE TITLE
Populate vocabulary groups randomly?

### ISSUE THREAD

**Issue by ashwinvis** [makkoncept/pyvoc#3]
Good job on this nice CLI tool. ~~Right now it serves well as a dictionary.~~

**EDIT**: I didn't notice that groups 101, 102, 103 exists until I looked manually at `~/.pyvoc`. I see that you have indeed pointed that in the README. Perhaps indicate that when you initialize  / when you do `pyvoc --list`.

I am not sure how the Oxford dictionary API works, but perhaps you can populate the vocabulary groups by loading from https://en.oxforddictionaries.com/explore/word-lists. Once there is such a functionality in place, it would be also nice to populate from other word lists freely available (if it exists, and it should).

**Comment by makkoncept** [comment]
hey @ashwinvis , I am sorry i didn't saw this issue. I forgot to turn on mail notifications.

Yes I have included this thing in the todo and will add it soon.

I had created this [definitions](https://github.com/makkoncept/definitions) repositories, from where pyvoc fetches its custom vocabulary groups at the time of config creation. I don't use Oxford API for this as requesting 3*800 words at every config creation is not a good idea. There are bunch of other groups which you can use, just copy them to `~/pyvoc`.  Thanks for linking this good resource, it will surely help in creation of new groups
