### ISSUE TITLE
Add a release tag of your last versión

### ISSUE THREAD

**Issue by turulomio** [makkoncept/pyvoc#5]
Hi 
Congrats for your code
I'll like to make a personal ebuild to automatize distribution of your code in my  [Gentoo Linux Portage](https://github.com/turulomio/myportage)
I think it's a good habit, to make releases in Github, adding tags to git
I see you have versions in pypi, but not here. 
Would you mind tagging the last version of your code.
Thanks

**Comment by makkoncept** [comment]
hi @turulomio , thanks for the advice. I would do it soon.

**Comment by makkoncept** [comment]
Hi @turulomio, I have tagged the latest release.
Thanks for suggesting it :)
