### ISSUE TITLE
Not installing correctly with pip 19.0.2 on sparkylinux-testing

### ISSUE THREAD

**Issue by kanliot** [makkoncept/pyvoc#6]
I am Not a python dev, so your  patience is requested.

Installed pip from the pip website, then installed pyvoc with sudo  pip install pyvoc.

So I get the following error

```
pyvoc execreble
Traceback (most recent call last):
  File "/usr/local/bin/pyvoc", line 6, in <module>
    from pyvoc.pyvoc import main
  File "/usr/local/lib/python2.7/dist-packages/pyvoc/pyvoc.py", line 12, in <module>
    from pyvoc.check_config import read_config_file, check_config_dir
ImportError: No module named check_config

```

I suppose it could be a missing check_config module, but that seems to be uninstallable in current pip, as well as pypitools is uninstallable.

**Comment by makkoncept** [comment]
hi @kanliot, I see that you are using pip for python2.7. 
even if you pass this error, you may face some problems as python2.7 is not supported. 
You can use python3.6+.  It must run fine then.

**Comment by kanliot** [comment]
so, I should install pip3, then install pyvoc with pip3?

**Comment by makkoncept** [comment]
yeah, that will do the trick.
